# Generated by Django 4.2.6 on 2023-10-23 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='depto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='app/fotos')),
            ],
        ),
        migrations.CreateModel(
            name='comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('detalle', models.CharField(max_length=600)),
                ('detalle_corto', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('S', 'Suspension de actividades'), ('C', 'Suspension de clases'), ('I', 'Informacion')], default='.', max_length=5)),
                ('visible', models.BooleanField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depto')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificador', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
