# Generated by Django 4.2.6 on 2023-10-24 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_depto_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='publicado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
