# Generated by Django 4.2.6 on 2023-10-24 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comunicado_modificado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='entidad',
            table='Entidad',
        ),
    ]
